### ISSUE TITLE
Hi, is the 12v power supply connector in 320pcb reversed? 

### ISSUE THREAD

**Issue by changliuxian** [MobiFlight/mobiflight-panels#91]
Hi, is the 12v power supply connector in 320pcb reversed? The power input port is facing inward after I associate the 3D model.
![QQ截图20220220143635](https://user-images.githubusercontent.com/47049761/154831713-100d7e6b-9693-427f-ba1c-60f29c445883.png)
![2](https://user-images.githubusercontent.com/47049761/154831720-2f44816f-b2c1-4734-9c2f-e84fedd97d1e.png)

**Comment by madmonkeyfpv** [comment]
There are a huge range of connectors available, so long as the top pin is kept +ve and the other two ground you may use whichever connector you like, orientation may vary however the pcb is designed for the connector to be on the rear.

Most users prefer to add jumper wires from the barrel connector on the pcb for the screen so that only one Power supply is needed to power both the screen and the pcb backlights
